# Generated by Django 5.0.7 on 2024-07-26 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table='categoria',
        ),
        migrations.AlterModelTable(
            name='type',
            table='tipo',
        ),
    ]
